# =============================================================================
# Platform MCP server — LiteLLM key + env file + Docker Compose deployment
#
# Apply:
#   terraform apply -target=null_resource.mcp_deploy
# =============================================================================

# ---------------------------------------------------------------------------
# LiteLLM virtual key for platform-mcp (no budget cap — platform service)
# ---------------------------------------------------------------------------
resource "null_resource" "litellm_key_mcp" {
  triggers = {
    service = "platform-mcp"
  }

  provisioner "local-exec" {
    command = <<-EOT
      http_code=$(curl -s -o /tmp/litellm_resp_platform-mcp.json \
        -w "%%{http_code}" \
        -X POST "${var.litellm_url}/key/generate" \
        -H "Authorization: Bearer ${var.litellm_master_key}" \
        -H "Content-Type: application/json" \
        -d '{
          "key_alias": "platform-mcp",
          "models": ["fast-model","balanced-model","vision-model","embedding","transcription-model"],
          "metadata": {"service": "platform-mcp"}
        }')
      response=$(cat /tmp/litellm_resp_platform-mcp.json 2>/dev/null)
      if [ "$http_code" = "200" ] && echo "$response" | python3 -c "import sys,json; d=json.load(sys.stdin); assert 'key' in d" 2>/dev/null; then
        mv /tmp/litellm_resp_platform-mcp.json /tmp/litellm_key_platform-mcp.json
      else
        echo "ERROR: LiteLLM key generation failed. HTTP $http_code. Body: $response" >&2
        exit 1
      fi
    EOT
  }
}

data "local_file" "litellm_key_mcp_file" {
  filename   = "/tmp/litellm_key_platform-mcp.json"
  depends_on = [null_resource.litellm_key_mcp]
}

locals {
  mcp_litellm_key_data = jsondecode(data.local_file.litellm_key_mcp_file.content)
  mcp_litellm_key      = local.mcp_litellm_key_data["key"]
}

# ---------------------------------------------------------------------------
# Write services/mcp/.env — picked up by docker-compose env_file
# ---------------------------------------------------------------------------
resource "local_file" "mcp_env" {
  filename        = "${path.root}/../services/mcp/.env"
  file_permission = "0600"
  content         = <<-ENV
    # Generated by platform-infra Terraform — DO NOT EDIT MANUALLY
    # Regenerate: cd platform-infra/terraform && terraform apply -target=null_resource.mcp_deploy

    MCP_API_KEY=${var.mcp_api_key}

    # SMTP
    SMTP_HOST=${var.mcp_smtp_host}
    SMTP_PORT=${var.mcp_smtp_port}
    SMTP_USER=${var.mcp_smtp_user}
    SMTP_PASSWORD=${var.mcp_smtp_password}
    SMTP_FROM=${var.mcp_smtp_from}

    # Twilio
    TWILIO_ACCOUNT_SID=${var.mcp_twilio_account_sid}
    TWILIO_AUTH_TOKEN=${var.mcp_twilio_auth_token}
    TWILIO_PHONE_NUMBER=${var.mcp_twilio_phone_number}

    # Tavily
    TAVILY_API_KEY=${var.mcp_tavily_api_key}

    # LiteLLM (generated by Terraform — do not set manually)
    LITELLM_API_KEY=${local.mcp_litellm_key}
  ENV

  depends_on = [
    null_resource.litellm_key_mcp,
    data.local_file.litellm_key_mcp_file,
  ]
}

# ---------------------------------------------------------------------------
# Build and start platform-mcp via Docker Compose
# ---------------------------------------------------------------------------
resource "null_resource" "mcp_deploy" {
  triggers = {
    env_hash = sha256(local_file.mcp_env.content)
  }

  provisioner "local-exec" {
    command     = "docker compose up -d --build platform-mcp"
    working_dir = "${path.root}/.."
  }

  depends_on = [local_file.mcp_env]
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
output "mcp_litellm_api_key" {
  description = "LiteLLM virtual key provisioned for platform-mcp"
  value       = local.mcp_litellm_key
  sensitive   = true
}
