# Caddy route for project: ${project_name}
# Generated by platform-infra Terraform
#
# `security_headers` and `body_limit` snippets are defined in
# infra/caddy/Caddyfile and imported here.

${project_name}-api.${domain} {
    import security_headers
    import body_limit
    reverse_proxy ${project_name}-api:${api_port}
}

${project_name}.${domain} {
    import security_headers
    import body_limit
    reverse_proxy ${project_name}-web:80
}

${project_name}-admin.${domain} {
    import security_headers
    import body_limit
    reverse_proxy ${project_name}-admin:80
}
