# Generated by platform-infra Terraform — DO NOT EDIT MANUALLY
# Project: ${project_name}
# Regenerate: cd platform-infra/terraform && terraform apply -target=module.${project_name}

# ── PostgreSQL ──────────────────────────────────────────────────
DATABASE_URL=postgresql+asyncpg://${project_name}:${pg_password}@${pg_host}:${pg_port}/${project_name}
BROADCASTER_URL=postgresql://${project_name}:${pg_password}@${pg_host}:${pg_port}/${project_name}

# ── Redis ───────────────────────────────────────────────────────
REDIS_URL=redis://platform-redis:6379/${redis_db}

# ── Keycloak ────────────────────────────────────────────────────
KEYCLOAK_URL=http://platform-keycloak:8080
KEYCLOAK_REALM=${kc_realm}
KEYCLOAK_CLIENT_ID=backend-service
KEYCLOAK_CLIENT_SECRET=${kc_client_secret}

# ── MinIO ───────────────────────────────────────────────────────
MINIO_ENDPOINT=platform-minio:9000
MINIO_ACCESS_KEY=${minio_access_key}
MINIO_SECRET_KEY=${minio_secret_key}
MINIO_BUCKET=${project_name}-images
MINIO_SECURE=false

# ── LiteLLM ─────────────────────────────────────────────────────
LITELLM_PROXY_URL=http://platform-litellm:4000
LITELLM_API_KEY=${litellm_key}

# ── Observability ────────────────────────────────────────────────
OTEL_EXPORTER_OTLP_ENDPOINT=http://platform-otel-collector:4317
OTEL_EXPORTER_OTLP_INSECURE=true
OTEL_RESOURCE_ATTRIBUTES=service.namespace=${project_name},deployment.environment=production
