#!/usr/bin/env bash
# =============================================================================
# platform-postgres-entrypoint.sh
#
# 1. Snapshots the current wal-g + AWS env into /etc/wal-g.env so the
#    cron-fired base-backup can source it (cron strips env).
# 2. Starts crond in the background. We expect cron to be a side process —
#    if it dies, postgres should still run.
# 3. Execs the upstream postgres docker-entrypoint with whatever CMD/args
#    the caller passed (typically `postgres -c archive_mode=on ...`).
#
# archive_command runs in postgres' own process env, so it inherits the
# wal-g vars without needing the env file.
# =============================================================================
set -e

log() { printf '[platform-postgres-entrypoint %s] %s\n' "$(date -u +%H:%M:%S)" "$*"; }

# Dump the relevant env vars to a file readable by postgres (cron runs the
# base-backup as user postgres). We only emit vars that exist — undefined
# server config doesn't poison cron's env with empty strings.
log "writing wal-g env snapshot to /etc/wal-g.env"
{
  echo "# Generated by platform-postgres entrypoint at $(date -u --iso-8601=seconds)"
  for var in \
      WALG_S3_PREFIX \
      WALG_COMPRESSION_METHOD \
      WALG_DELTA_MAX_STEPS \
      AWS_ACCESS_KEY_ID \
      AWS_SECRET_ACCESS_KEY \
      AWS_ENDPOINT \
      AWS_REGION \
      AWS_S3_FORCE_PATH_STYLE \
      PGDATA \
      PGHOST \
      PGUSER ; do
    val="${!var:-}"
    if [[ -n "${val}" ]]; then
      # printf %q handles paths and special chars safely.
      printf 'export %s=%q\n' "${var}" "${val}"
    fi
  done
} > /etc/wal-g.env
chmod 0640 /etc/wal-g.env
chown root:postgres /etc/wal-g.env

# Default PGHOST/PGUSER for the base-backup script if not already set —
# wal-g backup-push needs to talk to the running postgres over libpq.
if ! grep -q '^export PGUSER=' /etc/wal-g.env; then
  echo "export PGUSER=${POSTGRES_USER:-postgres}" >> /etc/wal-g.env
fi
if ! grep -q '^export PGHOST=' /etc/wal-g.env; then
  echo "export PGHOST=/var/run/postgresql" >> /etc/wal-g.env
fi

# PGPASSWORD has to be passed too so wal-g's libpq auth works against the
# running cluster. POSTGRES_PASSWORD is the bootstrap one.
if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
  echo "export PGPASSWORD=${POSTGRES_PASSWORD@Q}" >> /etc/wal-g.env
fi

# Start cron. If it fails (e.g. another cron already running), warn but
# don't kill the postgres boot — archive_command still works without cron;
# only the base-backup schedule depends on cron.
log "starting cron daemon"
if ! cron; then
  log "WARN: cron failed to start; weekly base-backup schedule will not run until restart"
fi

log "handing off to upstream docker-entrypoint.sh with args: $*"
exec /usr/local/bin/docker-entrypoint.sh "$@"
