apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://platform-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://platform-jaeger:16686
    jsonData:
      nodeGraph:
        enabled: true
